from typing import Dict, TYPE_CHECKING
import logging

from .Types import LocData
from .Options import get_goal_name

if TYPE_CHECKING:
    from . import BoboWorld

def did_include_sagas(world: "BoboWorld") -> bool:
    return bool(world.options.SagasEnabled)


def get_total_locations(world: "BoboWorld") -> int:
    total = 0
    for name in location_table:
        if is_valid_location(world, name):
            total += 1

    return total

def get_location_names() -> Dict[str, int]:
    names = {name: data.ap_code for name, data in location_table.items()}

    return names

def is_valid_location(world: "BoboWorld", name) -> bool:
    if name in saga_locations and not did_include_sagas(world):
        return False
    if name in event_locations:
        goal_asset = get_goal_name(world)
        if event_locations[name].asset_name != goal_asset:
            return False
    return True

bobo_locations = {
    # E Rank
    "Baby's First Steps (Race, E)": LocData(20050100, "Competitions", "BabysFirstSteps_Race_E", "E"),
    "Bigger Water Train (Race, E)": LocData(20050101, "Competitions", "BiggerWaterTrain_Race_E", "E"),
    "Comet O'Clock (Race, E)": LocData(20050102, "Competitions", "CometOClock_Race_E", "E"),
    "I Can Climb That (Race, E)": LocData(20050103, "Competitions", "ICanClimbThat_Race_E", "E"),
    "In The Drink (Brawl, E)": LocData(20050104, "Competitions", "InTheDrink_Brawl_E", "E"),
    "Lean Milk Baby (Brawl, E)": LocData(20050105, "Competitions", "LeanMilkBaby_Brawl_E", "E"),
    "Let's Try Climbing (Race, E)": LocData(20050106, "Competitions", "Let'sTryClimbing_Race_E", "E"),
    "Little Water Train (Race, E)": LocData(20050107, "Competitions", "LittleWaterTrain_Race_E", "E"),
    "Punch the Baby (Brawl, E)": LocData(20050108, "Competitions", "PunchTheBaby_Brawl_E", "E"),
    "Qwench (Race, E)": LocData(20050109, "Competitions", "Qwench_Race_E", "E"),
    "Still Crawling (Race, E)": LocData(20050110, "Competitions", "StillCrawling_Race_E", "E"),
    "Swim Lessons (Race, E)": LocData(20050111, "Competitions", "SwimLessons_Race_E", "E"),
    "The New Me (Race, E)": LocData(20050112, "Competitions", "TheNewMe_Race_E", "E"),
    "Up To The Moon (Race, E)": LocData(20050113, "Competitions", "UpToTheMoon_Race_E", "E"),

    # D Rank
    "Boy Alphard (Race, D)": LocData(20050114, "Competitions", "Alphard_Race_D", "D"),
    "Beam With a View (Race, D)": LocData(20050115, "Competitions", "BeamWithAView_Race_D", "D"),
    "Beefy (Brawl, D)": LocData(20050116, "Competitions", "Beefy_Brawl_D", "D"),
    "Big Jam (Race, D)": LocData(20050117, "Competitions", "BigJam_Race_D", "D"),
    "Channel It (Race, D)": LocData(20050118, "Competitions", "ChannelIt_Race_D", "D"),
    "Crawfish Coo (Brawl, D)": LocData(20050119, "Competitions", "CrawfishCoo_Brawl_D", "D"),
    "Double Kee Laps (Race, D)": LocData(20050120, "Competitions", "Double Kee Laps_Race_D", "D"),
    "Drippy (Brawl, D)": LocData(20050121, "Competitions", "Drippy_Brawl_D", "D"),
    "Little Longer Now (Race, D)": LocData(20050122, "Competitions", "LittleLongerNow_Race_D", "D"),
    "Mini Match (Brawl, D)": LocData(20050123, "Competitions", "MiniMatch_Brawl_D", "D"),
    "Muckula (Race, D)": LocData(20050124, "Competitions", "Muckula_Race_D_Relay", "D"),
    "Pow (Brawl, D)": LocData(20050125, "Competitions", "Pow_Brawl_D", "D"),
    "Pumpkick (Brawl, D)": LocData(20050126, "Competitions", "Pumpkick_Brawl_D", "D"),
    "Punch It (Race, D)": LocData(20050127, "Competitions", "PunchIt_Race_D", "D"),
    "Splish Block (Race, D)": LocData(20050128, "Competitions", "SplishBlock_Race_D", "D"),
    "Take Me Out (Brawl, D)": LocData(20050129, "Competitions", "TakeMeOut_Brawl_D", "D"),
    "Test the Jump (Race, D)": LocData(20050130, "Competitions", "TestTheJump_Race_D", "D"),
    "Through the Cave (Race, D)": LocData(20050131, "Competitions", "ThroughTheCave_Race_D", "D"),
    "Under The Scramble (Brawl, D)": LocData(20050132, "Competitions", "UndertheScramble_Brawl_D", "D"),
    "Vertical Doggy Paddle (Race, D)": LocData(20050133, "Competitions", "VerticalDoggyPaddle_Race_D", "D"),
    "Walk Along High (Race, D)": LocData(20050134, "Competitions", "WalkAlongHigh_Race_D", "D"),
    "Wavey Baby (Race, D)": LocData(20050135, "Competitions", "WaveyBaby_Race_D", "D"),
    "Woovy (Race, D)": LocData(20050136, "Competitions", "Woovy_Race_D", "D"),
    "You Jump, I Climb (Race, D)": LocData(20050137, "Competitions", "YouJumpIClimb_Race_D_Relay", "D"),

    # C Rank
    "Bring It (Brawl, C)": LocData(20050138, "Competitions", "BringIt_Brawl_C", "C"),
    "Coral (Race, C)": LocData(20050139, "Competitions", "Coral_Race", "C"),
    "Course and Rough (Race, C)": LocData(20050140, "Competitions", "CourseAndRough_Race_C", "C"),
    "Dinosaur Ken (Brawl, C)": LocData(20050141, "Competitions", "DinosaurKen_Brawl_C", "C"),
    "Discounted Island Tour (Race, C)": LocData(20050142, "Competitions", "DiscountedTour_Race_C_Relay", "C"),
    "Final Straw (Race, C)": LocData(20050143, "Competitions", "FinalStraw_Race_C", "C"),
    "Flower (Race, C)": LocData(20050144, "Competitions", "Flower_Race", "C"),
    "From the Top Rope (Race, C)": LocData(20050145, "Competitions", "FromTheTopRope_Race_C", "C"),
    "Glide Wandering (Race, C)": LocData(20050146, "Competitions", "GliderWandering_Race_C", "C"),
    "Happy New Year! (Race, C)": LocData(20050147, "Competitions", "HappyNewYear_Race_C", "C"),
    "Hotel Privago (Race, C)": LocData(20050148, "Competitions", "HotelPrivago_Race_C", "C"),
    "Late Night Jog (Race, C)": LocData(20050149, "Competitions", "LateNightJog_Race_C", "C"),
    "Oblivio (Race, C)": LocData(20050150, "Competitions", "Oblivio_Race_C", "C"),
    "Pick Me Corner (Race, C)": LocData(20050151, "Competitions", "PickMeCorner_Race_C_Relay", "C"),
    "Resist This (Brawl, C)": LocData(20050152, "Competitions", "ResistThis_Brawl_C", "C"),
    "Roundabout Rolled (Race, C)": LocData(20050153, "Competitions", "RoundaboutRolled_Race_C", "C"),
    "Stranded (Brawl, C)": LocData(20050154, "Competitions", "Stranded_Brawl_C", "C"),
    "Up and Over (Race, C)": LocData(20050155, "Competitions", "UpAndOver_Race_C", "C"),
    "Up the TAG (Race, C)": LocData(20050156, "Competitions", "UptheTAG_Race_C", "C"),
    "Walking on Water (Race, C)": LocData(20050157, "Competitions", "WalkingOnWater_Race_C", "C"),
    "Water Boarding (Race, C)": LocData(20050158, "Competitions", "WaterBoarding_Race_C", "C"),
    "Water Kee (Race, C)": LocData(20050159, "Competitions", "WaterKee_Race_C", "C"),
    "What is This Wall? (Race, C)": LocData(20050160, "Competitions", "WhatIsThisWall_Race_C", "C"),
    "Yoooo (Race, C)": LocData(20050161, "Competitions", "Yoooo_Race_C", "C"),

    # B Rank
    "Korn For Us (Race, B)": LocData(20050162, "Competitions", "AxeAway_Race_B", "B"),
    "Boulder (Race, B)": LocData(20050163, "Competitions", "Boulder_Race", "B"),
    "Bright Swim (Race, B)": LocData(20050164, "Competitions", "BrightSwim_Race_B", "B"),
    "Choose You (Race, B)": LocData(20050165, "Competitions", "ChooseYou_Race_B_Relay", "B"),
    "Cliff (Brawl, B)": LocData(20050166, "Competitions", "Cliff_Brawl", "B"),
    "Couple Caving (Race, B)": LocData(20050167, "Competitions", "CoupleCaving_Race_B_Relay", "B"),
    "Cream of Biceps (Race, B)": LocData(20050168, "Competitions", "CreamOfBiceps_Race_B", "B"),
    "Dangerous Walls (Race, B)": LocData(20050169, "Competitions", "DangerousWalls_Race_B", "B"),
    "Dark Swim (Race, B)": LocData(20050170, "Competitions", "DarkSwim_Race_B", "B"),
    "Day of the Doubloon (Race, B)": LocData(20050171, "Competitions", "DayOfTheDoubloon_Race_B", "B"),
    "Devil Pair (Race, B)": LocData(20050172, "Competitions", "DevilPair_Race_B_Relay", "B"),
    "Dinner Time (Brawl, B)": LocData(20050173, "Competitions", "DinnerTime_Brawl_B", "B"),
    "Froodoo (Race, B)": LocData(20050174, "Competitions", "Froodoo_Race_B", "B"),
    "Group Island Tour (Race, B)": LocData(20050175, "Competitions", "GroupIslandTour_Race_B", "B"),
    "Heardolls (Race, B)": LocData(20050176, "Competitions", "Heardolls_Race_B", "B"),
    "KB Vert (Race, B)": LocData(20050177, "Competitions", "KBVert_Race_B", "B"),
    "Late Night Scuffle (Brawl, B)": LocData(20050178, "Competitions", "LateNightScuffle_Brawl_B", "B"),
    "Leaf (Race, B)": LocData(20050179, "Competitions", "Leaf_Race", "B"),
    "Long Distance (Race, B)": LocData(20050180, "Competitions", "LongDistance_Race_B", "B"),
    "Long Jump (Race, B)": LocData(20050181, "Competitions", "LongJump_Race_B", "B"),
    "Milk Cert (Race, B)": LocData(20050182, "Competitions", "MilkCert_Race_B", "B"),
    "Non-Dairy (Brawl, B)": LocData(20050183, "Competitions", "NonDairy_Brawl_B", "B"),
    "Pier (Brawl, B)": LocData(20050184, "Competitions", "Pier_Brawl", "B"),
    "Quick Hands (Brawl, B)": LocData(20050185, "Competitions", "QuickHands_Brawl_B", "B"),
    "Rope Soap (Race, B)": LocData(20050186, "Competitions", "RopeSoap_Race_B", "B"),
    "Skater Boy (Race, B)": LocData(20050187, "Competitions", "SkaterBoy_Race_B", "B"),
    "Slow and Steady (Race, B)": LocData(20050188, "Competitions", "SlowAndSteady_Race_B", "B"),
    "5 Species Showcase (Race, B)": LocData(20050189, "Competitions", "SpeciesShowcase_Race", "B"),
    "Sticky Sit (Brawl, B)": LocData(20050190, "Competitions", "StickySit_Brawl_B", "B"),
    "Traffic Light (Race, B)": LocData(20050191, "Competitions", "TrafficLight_Race_B_Relay", "B"),

    # A Rank
    "Black Water (Race, A)": LocData(20050192, "Competitions", "BlackWater_Race_A_Relay", "A"),
    "Bound Up Bundle Up (Race, A)": LocData(20050193, "Competitions", "BoundUp_Race_A", "A"),
    "Clean Supreme (Race, A)": LocData(20050194, "Competitions", "CleanSupreme_Race_A", "A"),
    "Dark Doubloon (Race, A)": LocData(20050195, "Competitions", "DarkDoubloon_Race_A", "A"),
    "Dive (Race, A)": LocData(20050196, "Competitions", "Dive_Race", "A"),
    "Frontline (Race, A)": LocData(20050197, "Competitions", "Frontline_Race_A", "A"),
    "Galaxy Garden (Brawl, A)": LocData(20050198, "Competitions", "GalaxyGarden_Brawl_A", "A"),
    "Heaven Together (Race, A)": LocData(20050199, "Competitions", "HeavenTogether_Race_A_Relay", "A"),
    "Helicopter (Race, A)": LocData(20050200, "Competitions", "Helicopter_Race", "A"),
    "IRS (Brawl, A)": LocData(20050201, "Competitions", "IRS_Brawl_A", "A"),
    "Island Tour (Race, A)": LocData(20050202, "Competitions", "IslandTour_Race_A", "A"),
    "Lava Guava (Race, A)": LocData(20050203, "Competitions", "LavaGuava_Race_A", "A"),
    "Lumi Lumi Lumi (Race, A)": LocData(20050204, "Competitions", "LumiLumiLumi_Race_A", "A"),
    "Master Swordsman (Brawl, A)": LocData(20050205, "Competitions", "MasterSwordsman_Brawl_A", "A"),
    "Pool to Air (Race, A)": LocData(20050206, "Competitions", "PoolToAir_Race_A", "A"),
    "Stranded High (Brawl, A)": LocData(20050207, "Competitions", "StrandedHigh_Brawl_A", "A"),
    "This Spoon Is Taken (Race, A)": LocData(20050208, "Competitions", "ThisSpoonIsTaken_Race_A", "A"),
    "Very Important Person (Race, A)": LocData(20050209, "Competitions", "VIP_Race_A", "A"),
    "Wanna Help Me Jump? (Race, A)": LocData(20050210, "Competitions", "WannaHelpMeJump_A_Relay", "A"),
    "Water to Cliff (Race, A)": LocData(20050211, "Competitions", "WaterToCliff_Race_A", "A"),
    "Wet Walk (Race, A)": LocData(20050212, "Competitions", "WetWalk_Race_A", "A"),

    # S Rank
    "Aero Vine (Race, S)": LocData(20050213, "Competitions", "AeroVine_Race_S", "S"),
    "Alley (Brawl, S)": LocData(20050214, "Competitions", "Alley_Brawl", "S"),
    "Betelgeuse (Race, S)": LocData(20050215, "Competitions", "Betelgeuse_Race_S", "S"),
    "Cloud (Race, S)": LocData(20050216, "Competitions", "Cloud_Race", "S"),
    "The Dark Gauntlet (Race, S)": LocData(20050217, "Competitions", "DarkGauntlet_Race_S", "S"),
    "FIRE (Race, S)": LocData(20050218, "Competitions", "FIRE_Race_S", "S"),
    "Friendly Neighborhood (Race, S)": LocData(20050219, "Competitions", "FriendlyNeighborhood_Race_S", "S"),
    "The Gauntlet (Race, S)": LocData(20050220, "Competitions", "Gauntlet_Race_S", "S"),
    "Metro Party (Race, S)": LocData(20050221, "Competitions", "MetroParty_Race_S_Relay", "S"),
    "Mile High Lock (Brawl, S)": LocData(20050222, "Competitions", "MileHigh_Brawl_S", "S"),
    "Night Dippy (Race, S)": LocData(20050223, "Competitions", "NightDippy_Race_S", "S"),
    "No Touch (Brawl, S)": LocData(20050224, "Competitions", "NoTouch_Brawl_S", "S"),
    "Parallax (Race, S)": LocData(20050225, "Competitions", "Parallax_Race_S_Relay", "S"),
    "Puff Pounding (Brawl, S)": LocData(20050226, "Competitions", "PuffPounding_Brawl_S", "S"),
    "Pull Up Those Hips (Race, S)": LocData(20050227, "Competitions", "PullUpThoseHips_Race_S", "S"),
    "Rigel In Second (Race, S)": LocData(20050228, "Competitions", "RigelInSecond_Race_S", "S"),
    "Rock The Boat (Race, S)": LocData(20050229, "Competitions", "RockTheBoat_Race_S", "S"),
    "Run Run Run (Race, S)": LocData(20050230, "Competitions", "RunRunRun_Race_S", "S"),
    "Saddle Suds (Brawl, S)": LocData(20050231, "Competitions", "SadalSuds_Brawl_S", "S"),
    "Sadder Boys (Race, S)": LocData(20050232, "Competitions", "SadderBoys_Race_S", "S"),
    "True Sparkle (Race, S)": LocData(20050233, "Competitions", "TrueSparkle_Race_S", "S"),
    "Wind Around (Race, S)": LocData(20050234, "Competitions", "WindAround_Race_S", "S"),
    "With That Thang (Race, S)": LocData(20050235, "Competitions", "WithThatThang_Race_S", "S"),
}

saga_locations = {
    # Saga Competitions
    "First Dash (Saga Race, E)":                 LocData(20050300, "Sagas", "Race_E_FirstDash", "E"),
    "Second Dash (Saga Race, D)":                LocData(20050301, "Sagas", "Race_D_SecondDash", "D"),
    "Third Dash (Saga Race, C)":                 LocData(20050302, "Sagas", "Race_C_ThirdDash", "C"),
    "Fourth Dash (Saga Race, B)":                LocData(20050303, "Sagas", "Race_B_FourthDash", "B"),
    "Fifth Dash (Saga Race, A)":                 LocData(20050304, "Sagas", "Race_A_FifthDash", "A"),
    "Sixth Dash (Saga Race, S)":                 LocData(20050305, "Sagas", "Race_S_SixthDash", "S"),
    "Sky Kick (Saga Brawl, E)":                  LocData(20050306, "Sagas", "Brawl_E_SkyKick", "E"),
    "Twinkle Up (Saga Race, D)":                 LocData(20050307, "Sagas", "Race_D_TwinkleUp", "D"),
    "Teeny Croquette (Saga Race, C)":            LocData(20050308, "Sagas", "Race_C_TeenyCroquette", "C"),
    "Vamola Cola (Saga Race, B)":                LocData(20050309, "Sagas", "Race_B_VamolaCola", "B"),
    "First Wet (Saga Race, E)":                  LocData(20050310, "Sagas", "Race_E_FirstWet", "E"),
    "Second Wet (Saga Race, D)":                 LocData(20050311, "Sagas", "Race_D_SecondWet", "D"),
    "Third Wet (Saga Race, C)":                  LocData(20050312, "Sagas", "Race_C_ThirdWet", "C"),
    "Fourth Wet (Saga Race, B)":                 LocData(20050313, "Sagas", "Race_B_FourthWet", "B"),
    "Fifth Wet (Saga Race, A)":                  LocData(20050314, "Sagas", "Race_A_FifthWet", "A"),
    "Sixth Wet (Saga Race, S)":                  LocData(20050315, "Sagas", "Race_S_SixthWet", "S"),
    "Tizzy (Saga Race, E)":                      LocData(20050316, "Sagas", "Race_E_Tizzy", "E"),
    "Carbonated (Saga Race, D)":                 LocData(20050317, "Sagas", "Race_D1_Carbonated", "D"),
    "Eat Jump Game (Saga Race, D)":              LocData(20050318, "Sagas", "Race_D2_EatJumpGame", "D"),
    "Power Gary (Saga Race, S)":                 LocData(20050319, "Sagas", "Race_S_PowerGary", "S"),
    "Break Down (Saga Race, D)":                 LocData(20050320, "Sagas", "Race_D_BreakDown", "D"),
    "Have The Power (Saga Brawl, C)":            LocData(20050321, "Sagas", "Brawl_C_HaveThePower", "C"),
    "Bub The Beezle (Saga Race, B)":             LocData(20050322, "Sagas", "Race_B_BubTheBeezle", "B"),
    "Berry Bee (Saga Brawl, D)":                 LocData(20050323, "Sagas", "Brawl_D_BerryBee", "D"),
    "Amor We Go (Saga Race, C)":                 LocData(20050324, "Sagas", "Race_C1_Amor We Go", "C"),
    "Nana Boo (Saga Race, C)":                   LocData(20050325, "Sagas", "Race_C2_NanaBoo", "C"),
    "Welon Welon Welon (Saga Race, B)":          LocData(20050326, "Sagas", "Race_B_WelonWelonWelon", "B"),
    "Drop Kick (Saga Race, D)":                  LocData(20050327, "Sagas", "Race_D_DropKick", "D"),
    "Fist To A Gun Fight (Saga Race, B)":        LocData(20050328, "Sagas", "Race_B_FistToAGunFight", "B"),
    "Is This Cheating (Saga Race, S)":           LocData(20050329, "Sagas", "Race_S_IsThisCheating", "S"),
    "First Hop (Saga Race, E)":                  LocData(20050330, "Sagas", "Race_E_FirstHop", "E"),
    "Second Hop (Saga Race, D)":                 LocData(20050331, "Sagas", "Race_D_SecondHop", "D"),
    "Third Hop (Saga Race, C)":                  LocData(20050332, "Sagas", "Race_C_ThirdHop", "C"),
    "Fourth Hop (Saga Race, B)":                 LocData(20050333, "Sagas", "Race_B_FourthHop", "B"),
    "Fifth Hop (Saga Race, A)":                  LocData(20050334, "Sagas", "Race_A_FifthHop", "A"),
    "Sixth Hop (Saga Race, S)":                  LocData(20050335, "Sagas", "Race_S_SixthHop", "S"),
    "Indefatigable (Saga Brawl, B)":             LocData(20050336, "Sagas", "Brawl_B1_Indefatigable", "B"),
    "Robusticity (Saga Brawl, B)":               LocData(20050337, "Sagas", "Brawl_B2_Robusticity", "B"),
    "Peripatetic (Saga Brawl, A)":               LocData(20050338, "Sagas", "Brawl_A_Peripatetic", "A"),
    "Terrestrial (Saga Brawl, S)":               LocData(20050339, "Sagas", "Brawl_S1_Terrestrial", "S"),
    "Polymathic (Saga Brawl, S)":                LocData(20050340, "Sagas", "Brawl_S2_Polymathic", "S"),
    "Simple Beam (Saga Race, D)":                LocData(20050341, "Sagas", "Race_D_SimpleBeam", "D"),
    "Splash Board (Saga Race, C)":               LocData(20050342, "Sagas", "Race_C_SplashBoard", "C"),
    "Slalom (Saga Race, B)":                     LocData(20050343, "Sagas", "Race_B1_Slalom", "B"),
    "Across The Towers (Saga Race, B)":          LocData(20050344, "Sagas", "Race_B2_AcrossTheTowers", "B"),
    "The Kelp (Saga Race, A)":                   LocData(20050345, "Sagas", "Race_A_TheKelp", "A"),
    "VIV-O OPERA (Saga Race, C)":                LocData(20050346, "Sagas", "Race_C_VIV-O OPERA", "C"),
    "First Jug (Saga Race, E)":                  LocData(20050347, "Sagas", "Race_E_FirstJug", "E"),
    "Second Jug (Saga Race, D)":                 LocData(20050348, "Sagas", "Race_D_SecondJug", "D"),
    "Third Jug (Saga Race, C)":                  LocData(20050349, "Sagas", "Race_C_ThirdJug", "C"),
    "Fourth Jug (Saga Race, B)":                 LocData(20050350, "Sagas", "Race_B_FourthJug", "B"),
    "Fifth Jug (Saga Race, A)":                  LocData(20050351, "Sagas", "Race_A_FifthJug", "A"),
    "Sixth Jug (Saga Race, S)":                  LocData(20050352, "Sagas", "Race_S_SixthJug", "S"),
    "First Iron (Saga Race, E)":                 LocData(20050353, "Sagas", "Race_E_FirstIron", "E"),
    "Second Iron (Saga Race, D)":                LocData(20050354, "Sagas", "Race_D_SecondIron", "D"),
    "Third Iron (Saga Race, C)":                 LocData(20050355, "Sagas", "Race_C_Third_Iron", "C"),
    "Fourth Iron (Saga Race, B)":                LocData(20050356, "Sagas", "Race_B_FourthIron", "B"),
    "Fifth Iron (Saga Race, A)":                 LocData(20050357, "Sagas", "Race_A_FifthIron", "A"),
    "Sixth Iron (Saga Race, S)":                 LocData(20050358, "Sagas", "Race_S_SixthIron", "S"),
    "2 of Hearts (Saga Brawl, D)":               LocData(20050359, "Sagas", "Brawl_D_2ofHearts", "D"),
    "Bink (Saga Brawl, C)":                      LocData(20050360, "Sagas", "Brawl_C1_Bink", "C"),
    "Nano (Saga Brawl, C)":                      LocData(20050361, "Sagas", "Brawl_C2_Nano", "C"),
    "Kiki (Saga Brawl, B)":                      LocData(20050362, "Sagas", "Brawl_B_Kiki", "B"),
    "Moto (Saga Brawl, A)":                      LocData(20050363, "Sagas", "Brawl_A1_Moto", "A"),
    "Punk Brother (Saga Brawl, A)":              LocData(20050364, "Sagas", "Brawl_A2_PunkBrother", "A"),
    "Cat (Saga Race, D)":                        LocData(20050365, "Sagas", "Race_D_Cat", "D"),
    "Rhino (Saga Race, C)":                      LocData(20050366, "Sagas", "Race_C_Rhino", "C"),
    "Bunny (Saga Race, B)":                      LocData(20050367, "Sagas", "Race_B_Bunny", "B"),
    "Monkey (Saga Race, B)":                     LocData(20050368, "Sagas", "Race_B_Monkey", "B"),
    "Penguin (Saga Race, A)":                    LocData(20050369, "Sagas", "Race_A_Penguin", "A"),
    "Red (Saga Brawl, E)":                       LocData(20050370, "Sagas", "Brawl_E_Red", "E"),
    "Green (Saga Brawl, E)":                     LocData(20050371, "Sagas", "Brawl_E_Green", "E"),
    "Blue (Saga Brawl, D)":                      LocData(20050372, "Sagas", "Brawl_D_Blue", "D"),
    "Naked Feather (Saga Race, D)":              LocData(20050373, "Sagas", "Race_D_NakedFeather", "D"),
    "Ferry To Gondo (Saga Race, C)":             LocData(20050374, "Sagas", "Race_C_FerryToGondo", "C"),
    "Believe Me (Saga Brawl, B)":                LocData(20050375, "Sagas", "Brawl_B_BelieveMe", "B"),
    "See The Hero (Saga Race, A)":               LocData(20050376, "Sagas", "Race_A_SeeTheHero", "A"),
}

pubworks_locations = {
    "Public Works - Fix Benches":                       LocData(20050700, "Public Works", "PWP_FixBenches"),
    "Public Works - Basketball Hoop":                   LocData(20050701, "Public Works", "PWP_BasketballHoop"),
    "Public Works - Bench in Garden":                   LocData(20050702, "Public Works", "PWP_BenchInGarden"),
    "Public Works - Bobo Copy Machine":                 LocData(20050703, "Public Works", "PWP_BoboCopier"),
    "Public Works - Bobo Full Stat Viewer":             LocData(20050704, "Public Works", "PWP_BoboFullStatViewer"),
    "Public Works - Boombox":                           LocData(20050705, "Public Works", "PWP_Boombox"),
    "Public Works - Additional Camps":                  LocData(20050706, "Public Works", "PWP_CampUpgrade"),
    "Public Works - Cave Excursion":                    LocData(20050707, "Public Works", "PWP_Excursion_Caves"),
    "Public Works - Deep Forest Excursion":             LocData(20050708, "Public Works", "PWP_Excursion_DeepForest"),
    "Public Works - Gumball Machine":                   LocData(20050709, "Public Works", "PWP_GumballMachine"),
    "Public Works - Increase Competitions Per Day":     LocData(20050710, "Public Works", "PWP_IncreasedCompetitionsPerDay"),
    "Public Works - Increase Item Storage in Bayfarer": LocData(20050711, "Public Works", "PWP_IncreasedItemStorageInBoat"),
    "Public Works - Soccer Ball":                       LocData(20050712, "Public Works", "PWP_SoccerBall"),
    "Public Works - Storage Shed":                      LocData(20050713, "Public Works", "PWP_StorageShed"),
    "Public Works - Toy Blocks":                        LocData(20050714, "Public Works", "PWP_ToyBlocks"),
    "Public Works - Tree Farm Excursion":               LocData(20050715, "Public Works", "PWP_Excursion_TreeFarm"),
    "Public Works - TV":                                LocData(20050716, "Public Works", "PWP_TV"),
    "Public Works - Vending Machine":                   LocData(20050717, "Public Works", "PWP_VendingMachine"),
    "Public Works - Secret Garden":                     LocData(20050718, "Public Works", "PWP_SecretGarden"),
    "Public Works - Restaurant":                        LocData(20050719, "Public Works", "PWP_Restaurant"),
    "Public Works - Item Shop":                         LocData(20050720, "Public Works", "PWP_ItemShop"),
    "Public Works - Animal Cracker Shop":               LocData(20050721, "Public Works", "PWP_AnimalCrackerShop"),
    "Public Works - Costume Shop":                      LocData(20050722, "Public Works", "PWP_CostumeShop"),
    "Public Works - Original Bobo Statue":              LocData(20050723, "Public Works", "PWP_OriginalBoboStatue"),
    "Public Works - Fairy Garden":                      LocData(20050724, "Public Works", "PWP_SkyGarden"),
    "Public Works - Snack Shop Open at Night":          LocData(20050725, "Public Works", "PWP_SnackShopOpenAtNight"),
    "Public Works - Kelp Thrift Renovation":            LocData(20050726, "Public Works", "PWP_KelpThriftRenovation"),
    "Public Works - Fancy Shop":                        LocData(20050727, "Public Works", "PWP_FancyShop"),
    "Public Works - Exhibitions Terminal":              LocData(20050728, "Public Works", "PWP_ExhibitionsTerminal"),
    "Public Works - Rainbow in Garden":                 LocData(20050729, "Public Works", "PWP_RainbowInGarden"),
}

event_locations = {
    "Beat Big Jam":    LocData(None, "Competitions", "BigJam_Race_D", "D"),
    "Beat Power Gary": LocData(None, "Sagas", "Race_S_PowerGary", "S"),
}

location_table = {
    **bobo_locations,
    **saga_locations,
    **pubworks_locations,
    **event_locations,
}